"""
MindMate Content Generator
Hujjat, prezentatsiya, rasm va boshqa kontent yaratish moduli
"""

import io
import logging
from datetime import datetime
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

logger = logging.getLogger(__name__)

# === PDF GENERATION ===

def create_pdf_document(title, content, author="MindMate Bot"):
    """
    PDF hujjat yaratish

    Args:
        title: Hujjat sarlavhasi
        content: Hujjat matni (list yoki string)
        author: Muallif nomi

    Returns:
        BytesIO buffer with PDF content
    """
    try:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                              rightMargin=72, leftMargin=72,
                              topMargin=72, bottomMargin=18)

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor='#1a5490',
            spaceAfter=30,
            alignment=TA_CENTER
        )

        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['BodyText'],
            fontSize=12,
            alignment=TA_JUSTIFY,
            spaceAfter=12
        )

        # Build document
        story = []

        # Title
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 12))

        # Content
        if isinstance(content, str):
            content = content.split('\n')

        for paragraph in content:
            if paragraph.strip():
                story.append(Paragraph(paragraph.strip(), body_style))

        # Footer
        footer_text = f"Generated by MindMate Bot | {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, alignment=TA_CENTER)
        story.append(Spacer(1, 20))
        story.append(Paragraph(footer_text, footer_style))

        doc.build(story)
        buffer.seek(0)
        return buffer

    except Exception as e:
        logger.error(f"PDF yaratishda xato: {e}")
        return None


def create_resume_pdf(user_data):
    """
    Resume/CV PDF yaratish

    Args:
        user_data: Dict with resume data (name, email, experience, skills, etc.)

    Returns:
        BytesIO buffer with PDF content
    """
    try:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                              rightMargin=72, leftMargin=72,
                              topMargin=50, bottomMargin=18)

        styles = getSampleStyleSheet()
        story = []

        # Title (Name)
        name_style = ParagraphStyle('Name', parent=styles['Title'], fontSize=28, textColor='#1a5490')
        story.append(Paragraph(user_data.get('name', 'Your Name'), name_style))
        story.append(Spacer(1, 12))

        # Contact Info
        contact_style = ParagraphStyle('Contact', parent=styles['Normal'], fontSize=10, alignment=TA_CENTER)
        contact_info = f"{user_data.get('email', '')} | {user_data.get('phone', '')} | {user_data.get('location', '')}"
        story.append(Paragraph(contact_info, contact_style))
        story.append(Spacer(1, 20))

        # Summary
        if user_data.get('summary'):
            heading_style = ParagraphStyle('Heading', parent=styles['Heading2'], textColor='#1a5490')
            story.append(Paragraph('PROFESSIONAL SUMMARY', heading_style))
            story.append(Spacer(1, 6))
            story.append(Paragraph(user_data['summary'], styles['BodyText']))
            story.append(Spacer(1, 12))

        # Experience
        if user_data.get('experience'):
            story.append(Paragraph('WORK EXPERIENCE', heading_style))
            story.append(Spacer(1, 6))
            for exp in user_data['experience']:
                story.append(Paragraph(f"<b>{exp.get('title', '')}</b> - {exp.get('company', '')}", styles['BodyText']))
                story.append(Paragraph(f"<i>{exp.get('period', '')}</i>", styles['BodyText']))
                story.append(Paragraph(exp.get('description', ''), styles['BodyText']))
                story.append(Spacer(1, 8))

        # Skills
        if user_data.get('skills'):
            story.append(Paragraph('SKILLS', heading_style))
            story.append(Spacer(1, 6))
            skills_text = ', '.join(user_data['skills'])
            story.append(Paragraph(skills_text, styles['BodyText']))
            story.append(Spacer(1, 12))

        # Education
        if user_data.get('education'):
            story.append(Paragraph('EDUCATION', heading_style))
            story.append(Spacer(1, 6))
            for edu in user_data['education']:
                story.append(Paragraph(f"<b>{edu.get('degree', '')}</b> - {edu.get('school', '')}", styles['BodyText']))
                story.append(Paragraph(f"<i>{edu.get('year', '')}</i>", styles['BodyText']))
                story.append(Spacer(1, 8))

        doc.build(story)
        buffer.seek(0)
        return buffer

    except Exception as e:
        logger.error(f"Resume PDF yaratishda xato: {e}")
        return None


# === PRESENTATION GENERATION ===

def create_presentation(title, slides_data):
    """
    PowerPoint prezentatsiya yaratish

    Args:
        title: Prezentatsiya sarlavhasi
        slides_data: List of dicts with 'title' and 'content' for each slide

    Returns:
        BytesIO buffer with PPTX content
    """
    try:
        prs = Presentation()
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)

        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        subtitle = slide.placeholders[1]
        subtitle.text = f"Created by MindMate Bot\n{datetime.now().strftime('%Y-%m-%d')}"

        # Content Slides
        for slide_data in slides_data:
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)

            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]

            title_shape.text = slide_data.get('title', '')

            tf = body_shape.text_frame
            tf.clear()

            content = slide_data.get('content', [])
            if isinstance(content, str):
                content = content.split('\n')

            for item in content:
                if item.strip():
                    p = tf.add_paragraph()
                    p.text = item.strip()
                    p.level = 0

        buffer = io.BytesIO()
        prs.save(buffer)
        buffer.seek(0)
        return buffer

    except Exception as e:
        logger.error(f"Prezentatsiya yaratishda xato: {e}")
        return None


# === CONTENT TEMPLATES ===

def get_content_templates(lang="uz"):
    """Tayyor shablonlar"""
    templates = {
        "uz": {
            "study_plan": {
                "title": "O'quv Rejasi",
                "slides": [
                    {"title": "Maqsad", "content": ["Asosiy maqsad", "Kutilgan natijalar", "Muddat"]},
                    {"title": "1-hafta", "content": ["Mavzu 1", "Mavzu 2", "Amaliy mashg'ulot"]},
                    {"title": "2-hafta", "content": ["Mavzu 3", "Mavzu 4", "Loyiha ishi"]},
                    {"title": "Yakuniy baholash", "content": ["Imtihon", "Loyiha himoyasi", "Sertifikat"]}
                ]
            },
            "business_plan": {
                "title": "Biznes Reja",
                "slides": [
                    {"title": "Biznes g'oyasi", "content": ["Muammo", "Yechim", "Bozor imkoniyatlari"]},
                    {"title": "Mahsulot/Xizmat", "content": ["Tavsif", "Xususiyatlar", "Raqobatdosh ustunlik"]},
                    {"title": "Marketing strategiyasi", "content": ["Maqsadli auditoriya", "Marketing kanallari", "Byudjet"]},
                    {"title": "Moliyaviy rejalar", "content": ["Boshlang'ich investitsiya", "Daromad prognozi", "Foyda"]}
                ]
            }
        }
    }
    return templates.get(lang, templates["uz"])


# === LANGUAGE-SPECIFIC TEXT ===

def get_content_text(lang="uz"):
    """Content generator uchun tarjimalar"""
    return {
        "uz": {
            "pdf_created": "📄 PDF hujjat tayyor!",
            "ppt_created": "📊 Prezentatsiya tayyor!",
            "resume_created": "📋 Rezyume tayyor!",
            "enter_title": "📝 Sarlavhani kiriting:",
            "enter_content": "✍️ Matnni kiriting (har bir paragraf alohida qatorda):",
            "template_choose": "📚 Shablonni tanlang:",
            "error": "⚠️ Xatolik yuz berdi. Qaytadan urinib ko'ring."
        },
        "en": {
            "pdf_created": "📄 PDF document ready!",
            "ppt_created": "📊 Presentation ready!",
            "resume_created": "📋 Resume ready!",
            "enter_title": "📝 Enter title:",
            "enter_content": "✍️ Enter content (each paragraph on a new line):",
            "template_choose": "📚 Choose template:",
            "error": "⚠️ An error occurred. Please try again."
        },
        "ru": {
            "pdf_created": "📄 PDF документ готов!",
            "ppt_created": "📊 Презентация готова!",
            "resume_created": "📋 Резюме готово!",
            "enter_title": "📝 Введите заголовок:",
            "enter_content": "✍️ Введите текст (каждый абзац с новой строки):",
            "template_choose": "📚 Выберите шаблон:",
            "error": "⚠️ Произошла ошибка. Попробуйте еще раз."
        }
    }.get(lang, {})
